In [1]:
import numpy as np 


In [2]:
x= np.array([[1,4,5],
             [2,3,6],
             [3,5,7]])

In [3]:
# mean and variance 
from sklearn import preprocessing 
x_scale=preprocessing.scale(x)
print(x_scale.mean(axis=0))
x_scale.std(axis=0)

[0. 0. 0.]


array([1., 1., 1.])

In [4]:
y=np.array([[1,2,4],
           [2,3,4],
           [3,4,5]])

In [5]:
scale=preprocessing.StandardScaler()
scale.fit(x) 
print(scale.transform(y))
print("---------------------------------------")
print(scale.transform(x))

[[-1.22474487 -2.44948974 -2.44948974]
 [ 0.         -1.22474487 -2.44948974]
 [ 1.22474487  0.         -1.22474487]]
---------------------------------------
[[-1.22474487  0.         -1.22474487]
 [ 0.         -1.22474487  0.        ]
 [ 1.22474487  1.22474487  1.22474487]]
