In [1]:
import numpy as np

In [2]:
x=np.array([[0,0],[0,1],[1,0],[1,1]])
y=np.array([[0,0,0,1]]).T

x.shape,y.shape

((4, 2), (4, 1))

In [3]:
def sig(z):
    return 1/(1+np.exp(-z))

In [4]:
def derivative_sig(z):
    return sig(z)*(1-sig(z))

In [5]:
#weights=np.array([[70],[70]])
#bias=-100
weights=2*np.random.random((2,1))-1
bias=2*np.random.random(1)-1
lr=0.1
weights,bias


(array([[ 0.60431538],
        [-0.80465978]]),
 array([-0.20354412]))

In [6]:
for itr in range(10000):
    output=sig(np.dot(x,weights)+bias)
    first_term=output-y
    input_for_last_layer=np.dot(x,weights)+bias
    second_term=derivative_sig(input_for_last_layer)
    first_two=first_term*second_term
    #gradient
    change=np.dot(x.T,first_two)
    weights=weights-lr*change

    bias_change=first_two.sum()
    bias=bias-lr*bias_change
output=sig(np.dot(x,weights)+bias)
output,weights,bias

(array([[2.46736680e-04],
        [5.56830987e-02],
        [5.56831000e-02],
        [9.33725162e-01]]),
 array([[5.47615697],
        [5.47615695]]),
 array([-8.30694209]))